configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://db.qoqkxcfypayewptggavr.supabase.co/postgres?user=${process.env.SUPABASE_DB_NAME}&password=${process.env.SUPABASE_DB_PASSWORD}
